name: Build & Analyze Python with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del repo
      - name: Check out
        uses: actions/checkout@v3

      # 2. Instalar Python (ej. 3.10)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Correr las pruebas con coverage
      - name: Run coverage
        run: |
          coverage run -m unittest discover
          coverage xml

      # 5. Configurar Java 17 antes del escaneo
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 6. Analizar con SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.8
        with:
          args: >
            -Dsonar.projectKey=juan-construsoft_python-practicas
            -Dsonar.organization=juan-construsoft
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
