name: Build & Analyze Python with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run coverage
        run: |
          coverage run -m unittest discover
          coverage xml

      # 1) Instalas Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2) Ejemplo opcional: verifica la versión de Java
      - name: Check Java version
        run: java -version

      # 3) SonarCloud Scan con useGlobalJava: true
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.8
        with:
          # Fuerza a la acción a usar la Java instalada (17), en lugar del contenedor con Java 11
          useGlobalJava: true
          args: >
            -Dsonar.projectKey=juan-construsoft_python-practicas
            -Dsonar.organization=juan-construsoft
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=coverage.xml
