
name: SonarCloud Analysis (Local CLI)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run coverage
        run: |
          coverage run -m unittest discover
          coverage xml

      # 1) Instala Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2) Verifica la ruta de Java
      - name: Check Java
        run: |
          which java
          java -version

      # 3) Fuerza a que /usr/bin/java sea Java 17
      - name: Force Java 17 as default
        run: |
          sudo update-alternatives --install /usr/bin/java java "$(which java)" 2
          sudo update-alternatives --set java "$(which java)"
          java -version

      # 4) Instala SonarScanner CLI
      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          sudo mv sonar-scanner-4.8.0.2856-linux /usr/local/sonar-scanner
          sudo ln -s /usr/local/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      # 5) Ejecuta SonarScanner con Java 17
      - name: SonarScanner CLI
        run: 
          sonar-scanner 
            -Dsonar.projectKey=juan-construsoft_python-practicas 
            -Dsonar.organization=juan-construsoft 
            -Dsonar.host.url=https://sonarcloud.io 
            -Dsonar.python.coverage.reportPaths=coverage.xml 
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          
