name: SonarCloud Analysis (Local CLI)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
      # 1) Checkout
      - name: Check out
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Instalar dependencias (p.ej. coverage)
      - name: Install Python deps
        run: pip install -r requirements.txt

      # 4) Ejecutar pruebas y generar 'coverage.xml'
      - name: Run coverage
        run: |
          coverage run -m unittest discover
          coverage xml

      # 5) Instalar Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 6) (Verificación) Versión Java "antes" de update-alternatives
      - name: Check Java (before forcing)
        run: |
          echo "Before forcing default..."
          which java
          java -version

      # 7) Forzar Java 17 en /usr/bin/java
      - name: Force Java 17 as default
        run: |
          # 'which java' te debe dar algo tipo /opt/hostedtoolcache/Java_Adoptium_jdk/17.x.x/x64/bin/java
          # Forzamos que /usr/bin/java apunte a esa ruta.
          echo "Now forcing Java 17..."
          sudo update-alternatives --install /usr/bin/java java "$(which java)" 2
          sudo update-alternatives --set java "$(which java)"
          # Revisamos
          which java
          java -version

      # 8) Instalar SonarScanner CLI
      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          sudo mv sonar-scanner-4.8.0.2856-linux /usr/local/sonar-scanner
          sudo ln -sf /usr/local/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      # 9) Ejecutar SonarScanner CLI con Java 17
      - name: SonarScanner CLI
        run: |
          echo "Running SonarScanner CLI..."
          sonar-scanner 
            -Dsonar.projectKey=juan-construsoft_python-practicas 
            -Dsonar.organization=juan-construsoft 
            -Dsonar.host.url=https://sonarcloud.io 
            -Dsonar.python.coverage.reportPaths=coverage.xml 
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
