name: SonarCloud Analysis (Local CLI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
      # (A) Descarga el c贸digo
      - name: Check out
        uses: actions/checkout@v3

      # (B) Configura Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # (C) Instala dependencias (ej. coverage)
      - name: Install Python deps
        run: pip install -r requirements.txt

      # (D) Ejecuta pruebas y genera coverage.xml
      - name: Run coverage
        run: |
          coverage run -m unittest discover
          coverage xml

      # (E) Instala Java 17 con setup-java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # (F) Verifica la versi贸n de Java (antes de forzar)
      - name: Check Java (before forcing)
        run: |
          echo "=== Checking java BEFORE forcing ==="
          which java
          java -version

      # (G) Fuerza Java 17 en /usr/bin/java con update-alternatives
      - name: Force Java 17 as default
        run: |
          echo "=== Forcing Java 17 default ==="
          # 1. Observa la salida del paso anterior: la ruta exacta donde se instal贸 Java 17
          #    suele ser /opt/hostedtoolcache/Java_Adoptium_jdk/17.x.x/x64/bin/java
          # 2. Usa esa ruta en update-alternatives:
          sudo update-alternatives --install /usr/bin/java java "$(which java)" 2
          sudo update-alternatives --set java "$(which java)"
          echo "=== Java after forcing ==="
          which java
          java -version

      # (H) Instala SonarScanner CLI
      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          sudo mv sonar-scanner-4.8.0.2856-linux /usr/local/sonar-scanner
          # Importante: -sf para forzar el enlace simb贸lico
          sudo ln -sf /usr/local/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      # (I) Ejecuta SonarScanner CLI con Java 17
      - name: SonarScanner CLI
        run: |
          echo "=== Running SonarScanner CLI ==="
          sonar-scanner 
            -Dsonar.projectKey=juan-construsoft_python-practicas 
            -Dsonar.organization=juan-construsoft 
            -Dsonar.host.url=https://sonarcloud.io 
            -Dsonar.python.coverage.reportPaths=coverage.xml 
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
